modLoader = "javafml"
loaderVersion = "[47,)"
issueTrackerURL = "https://github.com/MisterJulsen/DragNSounds-API/issues"
license = "GNU General Public License v3.0"

[[mods]]
modId = "dragnsounds"
version = "${version}"
displayName = "DragNSounds API"
authors = "MrJulsen"
credits="JAVE2 by a-schild https://github.com/a-schild/jave2"
displayURL="https://misterjulsen.github.io/DragNSounds-API/"
description = '''
A simple API to upload custom sounds or music to the server and let them play in realtime to any player at any position without the need for a resourcepack. This project uses DragonLib, Architectury and JAVE2.
'''
logoFile = "icon.png"

[[dependencies.dragnsounds]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.dragnsounds]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.dragnsounds]]
modId = "architectury"
mandatory = true
versionRange = "[9.1.12,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.dragnsounds]]
modId = "dragonlib"
mandatory = true
versionRange = "[1.20.1-2.1.11,)"
ordering = "AFTER"
side = "BOTH"