modLoader = "javafml"
loaderVersion = "[40,)"
#issueTrackerURL = ""
license = "GNU General Public License v3.0"

[[mods]]
modId = "dragnsounds"
version = "${version}"
displayName = "DragNSounds API"
authors = "MrJulsen"
credits="JAVE2 by a-schild https://github.com/a-schild/jave2"
description = '''
A simple API to upload custom sounds or music to the server and let them play in realtime to any player at any position without the need for a resourcepack. This project uses DragonLib, Architectury and JAVE2.
'''
logoFile = "icon.png"

[[dependencies.dragnsounds]]
modId = "forge"
mandatory = true
versionRange = "[40,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.dragnsounds]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.dragnsounds]]
modId = "architectury"
mandatory = true
versionRange = "[4.11.93,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.dragnsounds]]
modId = "dragonlib"
mandatory = true
versionRange = "[1.18.2-2.1.8,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config="dragnsounds.mixins.json"
[[mixins]]
config="dragnsounds-common.mixins.json"