# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx6G
org.gradle.parallel=true

# Mod properties
mod_version = 0.2.1
release_channel = beta
maven_group = de.mrjulsen.dragnsounds
archives_name = dragnsounds
enabled_platforms = fabric,neoforge
includeDependencies = true
java_version = 17
datapack_version = 26

# Mod Info
display_name = DragNSounds API
authors = MrJulsen
description = A simple API to upload custom sounds or music to the server and let them play in realtime to any player at any position without the need for a resourcepack. This project uses DragonLib, Architectury and JAVE2.
homepage = https://www.curseforge.com/minecraft/mc-mods/dragnsounds-api
issues = https://github.com/MisterJulsen/DragNSounds-API/issues
source = https://github.com/MisterJulsen/DragNSounds-API
license = GNU General Public License v3.0
icon = icon.png
discord = https://discord.gg/AeSbNgvc7f

# Minecraft properties
minecraft_version = 1.20.4
parchment_version=2024.04.14
next_unsupported_minecraft_version=1.21

# Dependencies
architectury_api_version = 11.1.17
fabric_loader_version = 0.16.6
fabric_api_version = 0.97.2+1.20.4
neoforge_version = 20.4.237
neoforge_loader_version = 2
neoforge_dependency_version = 20.4

dragonlib_version = 2.2.24
modmenu_version=9.2.0
text_placeholder_api_version=2.4.0-pre.1+1.20.4
forge_config_api_port_version=20.4.3
jave_version=3.5.0