# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx6G
org.gradle.parallel=true

# Mod properties
mod_version = 0.2.1
release_channel = beta
maven_group = de.mrjulsen.dragnsounds
archives_name = dragnsounds
enabled_platforms = fabric,forge
includeDependencies = true
java_version = 17
datapack_version = 9

# Mod Info
display_name = DragNSounds API
authors = MrJulsen
description = A simple API to upload custom sounds or music to the server and let them play in realtime to any player at any position without the need for a resourcepack. This project uses DragonLib, Architectury and JAVE2.
homepage = https://www.curseforge.com/minecraft/mc-mods/dragnsounds-api
issues = https://github.com/MisterJulsen/DragNSounds-API/issues
source = https://github.com/MisterJulsen/DragNSounds-API
license = GNU General Public License v3.0
icon = icon.png
discord = https://discord.gg/AeSbNgvc7f

# Minecraft properties
minecraft_version = 1.20.1
parchment_version = 2023.09.03
next_unsupported_minecraft_version = 1.20.4

# Dependencies
architectury_api_version = 9.1.12
fabric_loader_version = 0.15.11
fabric_api_version = 0.90.4+1.20.1
forge_version = 1.20.1-47.2.1
forge_loader_version = 47
forge_dependency_version = 47

dragonlib_version = 2.2.24
modmenu_version=7.2.2
forge_config_api_port_version=8.0.0
jave_version=3.5.0