site_name: DragNSounds API Documentation
repo_url: https://github.com/MisterJulsen/DragNSounds-API
copyright: Copyright &copy; 2024 MrJulsen
extra:
  social:
    - icon: fontawesome/brands/discord
      name: Join Discord
      link: https://discord.gg/AeSbNgvc7f      
    - icon: fontawesome/brands/github
      name: Source on GitHub
      link: https://github.com/MisterJulsen/DragNSounds-API
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.path
    - navigation.top
    - navigation.indexes
    - navigation.footer
  icon:
    repo: fontawesome/brands/github
  logo: assets/icon.png
  favicon: assets/icon.png
  palette:

    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference